### ISSUE TITLE
Rating lock not working

### ISSUE THREAD

**Issue by Ma-ryan** [vesta42/myimouto-plus#12]
Ticking the rating locked box doesn't do anything.

**Comment by vesta42** [comment]
There is a function `setRating()` in RatingMethods.php but this function does not appear to be called from anywhere. Indeed it seems there is no code to enforce rating locked anywhere. Commit a653cb5 adds code to reject rating changes from users less than privileged when rating is locked. Privileged users and higher can still change rating, since they can also change rating locked.
