### ISSUE TITLE
Browse mode broke

### ISSUE THREAD

**Issue by Ma-ryan** [vesta42/myimouto-plus#14]
I'm not sure when this happened since I don't really use it, but someone sent me an email complaining about it and sure enough nothing loads anymore when using it.

**Comment by vesta42** [comment]
This seems to be caused in part by commit e07bb40. It is odd that removing the frames fields from the API causes JavaScript errors even though those fields are otherwise always empty. There still seems to be something else also causing the JavaScript to break; I am not sure what. I will have to go through each of the API related commits to see what is causing the problem.

**Comment by vesta42** [comment]
@Ma-ryan Please try reverting the changes of commit e07bb40 and see if it works for you afterwords.

Once I do that, the image browser loads. But when I hit space to bring up the overlay info, no thumbnails show up for other images. I thought there was supposed to be a row of thumbnails at the bottom to navigate between images or am I misremembering this? Also the hotkeys to navigate don't seem to work and scroll wheel to zoom doesn't work.

However... I am seeing the exact same thing on yande.re. No thumbnails, and navigation hotkeys and scroll wheel to zoom are not working there either. So I don't think that is caused by any changes I made.

**Comment by Ma-ryan** [comment]
Uncommenting the code in ApiMethods.php is enough to make it work again.

AFAIK, the space bar is supposed to hide the UI, which works as expected for me. The scroll wheel scrolls through the thumbnails at the bottom. The main difference that I can immediately see between current MyImouto and Moebooru on yande.re is that large images scale to fit the window over there whereas we get a small thumbnail on the top right to scroll around the image.

The only keyboard shortcut that doesn't seem to work for me is the v key, which is supposed to zoom in/out.
