### ISSUE TITLE
Combining tag search from post pages

### ISSUE THREAD

**Issue by Ma-ryan** [vesta42/myimouto-plus#19]
The plus/minus sign next to tags in posts should include/exclude your current search with the desired tag. Clicking on it starts a new tag search with that tag only instead. Danbooru remembers your search when viewing a post, but that seems missing in MyImouto.

**Comment by vesta42** [comment]
The way Danbooru does it is by passing the search query over the URL which is probably the best way. But I think "pretty" URLs would interfere with this. These pretty URLs also interfere with client side caching and search engine ranking since when the tags change, the browser and search engine see it as a different page. It would probably be best to disable pretty URLs.

**Comment by Ma-ryan** [comment]
Getting rid of pretty URLs is a good idea. They are more annoying than they are useful.
